# Generated by Django 5.2.8 on 2026-04-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_user_avatar_alter_user_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="audio_muted",
            field=models.BooleanField(default=False, verbose_name="静音状态"),
        ),
    ]
