# Generated by Django 5.2.8 on 2026-04-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_user_audio_muted"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
