# Generated by Django 5.2.8 on 2026-04-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_remove_message_audio_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
