# Generated by Django 5.2.8 on 2026-04-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_message_audio_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="audio_url",
        ),
    ]
